[package]
name = "spellwell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spell_well = { path = "../spell_well" }
clap = { version = "4.1.8", features = ["derive"] }
